[deploy]
startCommand = "python manage.py migrate && python manage.py criar_admin && python manage.py criar_grupos && gunicorn setup.wsgi --log-file - --workers 1 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
