# Generated by Django 6.0.4 on 2026-04-08 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=20, verbose_name='Nº Pedido de Compra')),
                ('inicio', models.DateTimeField(verbose_name='Horário de Início')),
                ('fim_estimado', models.DateTimeField(blank=True, null=True, verbose_name='Fim Estimado')),
                ('tipo_carga', models.CharField(choices=[('PAL', 'Paletizada'), ('BAT', 'Batida'), ('FRA', 'Fracionada')], default='PAL', max_length=3, verbose_name='Tipo de Carga')),
                ('qtd_itens', models.IntegerField(default=1, verbose_name='Qtd. Itens/Caixas')),
                ('status', models.CharField(choices=[('PRE_AGENDADO', 'Pré-agendado'), ('CONFIRMADO', 'Confirmado'), ('EM_PATIO', 'Em pátio'), ('EM_DESCARGA', 'Em descarga'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('NO_SHOW', 'No-show')], default='PRE_AGENDADO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('chave_nfe', models.CharField(blank=True, max_length=44, null=True, unique=True, verbose_name='Chave NF-e')),
                ('arquivo_xml', models.FileField(blank=True, null=True, upload_to='xmls/%Y/%m/', verbose_name='XML da NF-e')),
                ('nfe_validada', models.BooleanField(default=False, verbose_name='NF-e Validada?')),
                ('nfe_vinculada_em', models.DateTimeField(blank=True, null=True, verbose_name='NF-e Vinculada em')),
                ('codigo_descarga', models.CharField(blank=True, max_length=4, null=True, verbose_name='Código de Descarga')),
                ('horario_chegada_real', models.DateTimeField(blank=True, null=True, verbose_name='Chegada Real')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Doca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('tipo_maximo', models.CharField(choices=[('VUC', 'VUC'), ('TOC', 'Toco'), ('TRU', 'Truck'), ('CAR', 'Carreta'), ('BIT', 'Bitrem')], max_length=3, verbose_name='Veículo Máximo')),
                ('temperatura_controlada', models.BooleanField(default=False, verbose_name='Câmara Fria?')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Doca',
                'verbose_name_plural': 'Docas',
            },
        ),
        migrations.CreateModel(
            name='EmpresaOperadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Empresa Operadora',
                'verbose_name_plural': 'Empresas Operadoras',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('score_pontualidade', models.FloatField(default=100.0, verbose_name='Score (0-100)')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Bloqueio Fiscal')),
                ('motivo_bloqueio', models.TextField(blank=True, verbose_name='Motivo do Bloqueio')),
                ('permite_multi_doca', models.BooleanField(default=False, verbose_name='Permite Multi-Doca?')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoDoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agendamento')),
                ('doca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.doca')),
            ],
            options={
                'verbose_name': 'Doca do Agendamento',
                'verbose_name_plural': 'Docas do Agendamento',
                'unique_together': {('agendamento', 'doca')},
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='docas',
            field=models.ManyToManyField(through='core.AgendamentoDoca', to='core.doca', verbose_name='Docas'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor'),
        ),
        migrations.CreateModel(
            name='LogAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=50, verbose_name='Status Novo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.agendamento')),
            ],
            options={
                'verbose_name': 'Log de Agendamento',
                'verbose_name_plural': 'Logs de Agendamento',
                'ordering': ['-data'],
            },
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['status'], name='core_agenda_status_015542_idx'),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['inicio'], name='core_agenda_inicio_216475_idx'),
        ),
    ]
