# Generated by Django 6.0.4 on 2026-04-10 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedor_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Acesso'),
        ),
    ]
