# Generated by Django 6.0.4 on 2026-04-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adiciona_user_email_ao_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='horario_entrada_patio',
            field=models.DateTimeField(blank=True, help_text='Preenchido automaticamente no check-in.', null=True, verbose_name='Entrada no Pátio'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario_finalizacao',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando a descarga é concluída.', null=True, verbose_name='Finalização'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario_inicio_descarga',
            field=models.DateTimeField(blank=True, help_text='Preenchido quando o gestor inicia a descarga.', null=True, verbose_name='Início da Descarga'),
        ),
    ]
