# Generated by Django 6.0.4 on 2026-04-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_v0_8_timestamps_patio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamentodoca',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logagendamento',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='agendamento',
            name='core_agenda_status_015542_idx',
        ),
        migrations.RemoveIndex(
            model_name='agendamento',
            name='core_agenda_inicio_216475_idx',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_entrada_patio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrada no Pátio'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_finalizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalização'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_inicio_descarga',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Descarga'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('PRE_AGENDADO', 'Pré-agendado'), ('AGUARDANDO_FISCAL', 'Em Análise Fiscal'), ('CONFIRMADO', 'Confirmado'), ('EM_PATIO', 'Em pátio'), ('EM_DESCARGA', 'Em descarga'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('NO_SHOW', 'No-show')], default='PRE_AGENDADO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='logagendamento',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logagendamento',
            name='status_anterior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logagendamento',
            name='status_novo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='logagendamento',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
