# Generated by Django 6.0.4 on 2026-04-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_agendamentodoca_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='chave_nfe',
            field=models.CharField(blank=True, max_length=4500, null=True, verbose_name='Chave NF-e'),
        ),
        migrations.CreateModel(
            name='NFeArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=44, verbose_name='Chave NF-e')),
                ('arquivo', models.FileField(upload_to='xmls/%Y/%m/', verbose_name='XML')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfe_arquivos', to='core.agendamento')),
            ],
            options={
                'verbose_name': 'Arquivo NF-e',
                'verbose_name_plural': 'Arquivos NF-e',
                'ordering': ['criado_em'],
            },
        ),
    ]
