# Generated by Django 6.0.4 on 2026-04-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_agendamento_chave_nfe_nfearquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfearquivo',
            name='aprovado',
            field=models.BooleanField(default=None, null=True, verbose_name='Aprovado'),
        ),
    ]
