# Generated by Django 5.2.14 on 2026-05-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_nfearquivo_aprovado"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="tipo_operacao",
            field=models.CharField(
                choices=[("DIRETA", "Direta Distribuidora"), ("CROSS", "Crossdocking")],
                default="DIRETA",
                max_length=10,
                verbose_name="Tipo de Operação",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="docas",
            field=models.ManyToManyField(
                blank=True,
                through="core.AgendamentoDoca",
                to="core.doca",
                verbose_name="Docas",
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRE_AGENDADO", "Pré-agendado"),
                    ("AGUARDANDO_FISCAL", "Pré-entrada Fiscal"),
                    ("CONFIRMADO", "Confirmado"),
                    ("EM_PATIO", "Em pátio"),
                    ("EM_DESCARGA", "Em descarga"),
                    ("FINALIZADO", "Finalizado"),
                    ("CANCELADO", "Cancelado"),
                    ("NO_SHOW", "No-show"),
                ],
                default="PRE_AGENDADO",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
