# Generated by Django 5.2.14 on 2026-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_tipo_operacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfearquivo",
            name="tipo_arquivo",
            field=models.CharField(
                choices=[("XML", "XML"), ("PDF", "PDF")],
                default="XML",
                max_length=3,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="nfearquivo",
            name="arquivo",
            field=models.FileField(upload_to="xmls/%Y/%m/", verbose_name="Arquivo"),
        ),
        migrations.AlterField(
            model_name="nfearquivo",
            name="chave",
            field=models.CharField(
                blank=True, default="", max_length=44, verbose_name="Chave NF-e"
            ),
        ),
    ]
