# Generated by Django 5.2.14 on 2026-05-18 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_nfearquivo_tipo_arquivo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=200, verbose_name="Razão Social"),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=14, verbose_name="CNPJ"),
                ),
                (
                    "email_contato",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail de Contato"
                    ),
                ),
                (
                    "dias_transito",
                    models.IntegerField(
                        default=2, verbose_name="Dias de trânsito até loja"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cliente Final",
                "verbose_name_plural": "Clientes Finais",
                "ordering": ["razao_social"],
            },
        ),
        migrations.CreateModel(
            name="PedidoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pedido_cliente",
                    models.CharField(
                        max_length=50, verbose_name="Nº do Pedido do Cliente"
                    ),
                ),
                (
                    "tipo_atendimento",
                    models.CharField(
                        choices=[("INTEGRAL", "Integral"), ("PARCIAL", "Parcial")],
                        default="INTEGRAL",
                        max_length=10,
                        verbose_name="Tipo de Atendimento",
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "agendamento",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedido_cliente",
                        to="core.agendamento",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="core.cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Cliente",
                "verbose_name_plural": "Pedidos de Clientes",
                "ordering": ["-criado_em"],
            },
        ),
    ]
