# Generated by Django 5.2.14 on 2026-05-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_cliente_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="dias_transito",
        ),
    ]
