# Generated by Django 5.2.14 on 2026-05-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_cliente_dias_transito"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="agenda_fixa",
            field=models.BooleanField(default=False, verbose_name="Grade Fixa?"),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="cor_marca",
            field=models.CharField(
                blank=True, default="", max_length=7, verbose_name="Cor da Marca"
            ),
        ),
        migrations.CreateModel(
            name="SlotFixo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda"),
                            (1, "Terça"),
                            (2, "Quarta"),
                            (3, "Quinta"),
                            (4, "Sexta"),
                        ],
                        verbose_name="Dia da Semana",
                    ),
                ),
                ("hora", models.IntegerField(verbose_name="Hora")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("HEINEKEN", "Heineken"),
                            ("PEPSICO", "PepsiCo"),
                            ("CROSS", "Crossdocking"),
                            ("DIRETA", "AG Simões"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Slot Fixo",
                "verbose_name_plural": "Slots Fixos",
                "ordering": ["dia_semana", "hora"],
                "unique_together": {("dia_semana", "hora")},
            },
        ),
    ]
