# Generated by Django 5.2.14 on 2026-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_agenda_fixa_slotfixo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendamento",
            options={
                "ordering": ["data_agendamento", "lacuna_numero"],
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
            },
        ),
        migrations.AddField(
            model_name="agendamento",
            name="data_agendamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Agendamento"
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="lacuna_numero",
            field=models.IntegerField(blank=True, null=True, verbose_name="Lacuna Nº"),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Horário de Início"
            ),
        ),
    ]
